USE [master]
GO

/****** Object:  Database [PatientDB]    Script Date: 9/28/2022 8:00:31 AM ******/
CREATE DATABASE [PatientDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PatientDB', FILENAME = N'E:\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PatientDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PatientDB_log', FILENAME = N'E:\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PatientDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PatientDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PatientDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PatientDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PatientDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PatientDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PatientDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PatientDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PatientDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PatientDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PatientDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PatientDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PatientDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PatientDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PatientDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PatientDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PatientDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PatientDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PatientDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PatientDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PatientDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PatientDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PatientDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PatientDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PatientDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PatientDB] SET  MULTI_USER 
GO

ALTER DATABASE [PatientDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PatientDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PatientDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PatientDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PatientDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PatientDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PatientDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PatientDB] SET  READ_WRITE 
GO

